### ISSUE TITLE
Show an Up arrow when you're in nonroot folders on contents tab 

### ISSUE THREAD

**Issue by mcdonc** [Pylons/substanced#144]
Be nice to have an up arrow over the button row so you don't have to pull your mouse up to the breadcrumbs.

**Comment by bphirokiky** [comment]
Does it mean action like `cd ..` ?

**Comment by cguardia** [comment]
I think just a link to the folder above the current one (the parent), whenever that is not the root itself.

**Comment by hirokiky** [comment]
memo: 

I found a change to comment out the button c5c34ff6ee127af0b437388cbf4b2695f3c8659f
seems @mcdonc didn't like that design. 

now uncommented, you can see like this
![uparrow](https://cloud.githubusercontent.com/assets/854049/8179617/cf6be91a-1452-11e5-95c7-0603bc8fc856.png)

**Comment by stevepiercy** [comment]
I think @mcdonc disliked the color. See this demo with alternative glyphicons: http://jsfiddle.net/stevepiercy/fno0pr7n/
* glyphicon-level-up
* glyphicon-menu-up
* glyphicon-chevron-up
* glyphicon-arrow-up
* glyphicon-hand-up

**Comment by dairiki** [comment]
I know nobody asked, but my 2¢: I vote for glyphicon-level-up as being the most clear.
(Though I'd vote for glyphicon-hand-up if it used the other finger ;-)

**Comment by hirokiky** [comment]
seems there are not level-up and menu-up on the 3.0.0 version of bootstrap (included in this project).

**Comment by cguardia** [comment]
Confirmed those icons are not there, so keeping the one that works for now.
