### ISSUE TITLE
Implement multi file upload

### ISSUE THREAD

**Issue by reebalazs** [Pylons/substanced#227]
[jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload) is the current leading component for file uploads. The goal is to integrate it to the admin interface (SDI) of Substance D.

The code is on branch `feature.multifileupload`.

I started to work on this on the Pycon Montreal sprint in 2014 April, and continued since then. The branch is getting ready for submission soon, there are only a few things left to do. I will present it briefly in case someone wants to comment.

- Works for all folders, each folder gets an Upload tab
- Controls
  * Single or multiple files can be added from Add button
  * Entire folders can be added too (their files only, not their structure)
  * Add files from OS by drag and drop, on capable devices
  * Cancelling added images before upload is possible
  * Upload and Abort buttons to control the upload process
- Displaying information 
  * Individual file status with name, size, modification, and progress bar
  * Mime type icons
  * For images, preview thumbnail
  * Global status with number of files, global size, speed, and global progress bar
- Visual enhancements
   * Smart scrolling
   * Status dismissal removes its associated elements
   * Works for all device sizes.

This video shows a short demo if you want to have a quick look without installing it.

Comments and opinions are welcome!

[![Play Video](https://dl.dropboxusercontent.com/u/16162405/sdi-multi-file-upload-intro_video_thumb.png)](https://vimeo.com/98848252)

**Comment by cguardia** [comment]
Merged into core with https://github.com/Pylons/substanced/commit/515fbfc7c2084c43b5b034a96a9a1a1197e7ac29

**Comment by cguardia** [comment]
Great Work!
