### ISSUE TITLE
Auditlog size documented as 10000 items but is of 1000

### ISSUE THREAD

**Issue by pallix** [Pylons/substanced#241]
The documentation about the [Auditing](https://github.com/Pylons/substanced/blame/fc8dd2248f96070b7d02797c28791d86694032d4/docs/audit.rst#L14) tells that 10000 items are kept in the auditlog, but in the implementation 1000 items are kept, as we can see in the constructor of the [AuditLog](https://github.com/Pylons/substanced/blob/fc8dd2248f96070b7d02797c28791d86694032d4/substanced/audit/__init__.py#L183).

**Comment by cguardia** [comment]
Fixed on https://github.com/Pylons/substanced/commit/54061bf0637fe8eaa51b4676456cee4752a827bb
