### ISSUE TITLE
Update docs for MacOS

### ISSUE THREAD

**Issue by Themanwithoutaplan** [Pylons/substanced#258]
The libmagic stuff is no longer relevant for MacOS. I'l write some tests for checking and update the docs.

**Comment by stevepiercy** [comment]
On which versions of Mac OS X is this no longer relevant? It might still be on 10.7 and 10.8.

**Comment by Themanwithoutaplan** [comment]
When I get my MacMini back I can test with Lion but this and systems running it are no longer supported by Apple. I'll also check whether it's one of the many Apple system Python problems. Normally not a problem if you use MacPorts, Brew or Python from python.org

**Comment by stevepiercy** [comment]
FWIW, I did have to do the libmagic dance on 10.8.5.

**Comment by Themanwithoutaplan** [comment]
What Python were you using? TBH must I a despise Apple for failing to support the hardware (64-bit Intel) because they can't be bothered to a 64-bit graphic driver I really don't think there will be many dev systems out there on 10.8

**Comment by Themanwithoutaplan** [comment]
This was resolved in the `update_python_matrix` PR
