### ISSUE TITLE
Drop 2.6 and 3.2 from the docs.

### ISSUE THREAD

**Issue by Themanwithoutaplan** [Pylons/substanced#259]
Webby stuff shouldn't really be using unsupported Python versions and Python 3.2 is just painful anyway.

**Comment by stevepiercy** [comment]
- Add 3.5. This probably means using the "matrix" from Pyramid.
- Update all the things (setup.py, tox, etc.) to reflect currently supported versions. For examples, see https://github.com/Pylons/pyramid/search?q=3.5&type=Issues&utf8=%E2%9C%93

**Comment by Themanwithoutaplan** [comment]
Fine to defer the versions to "what Pyramid" supports.

**Comment by Themanwithoutaplan** [comment]
This was resolved in the `update_python_matrix`PR
