### ISSUE TITLE
Docs not searchable on RTD, but are searchable on localhost

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/substanced#282]
http://docs.pylonsproject.org/projects/substanced/en/latest/search.html?q=install

JavaScript console:

Uncaught ReferenceError: $ is not defined(anonymous function) @ search.html?q=install:151

**Comment by stevepiercy** [comment]
#283 fixed the javascript error, but not the searchability. Search works on localhost, but not on RTD.

The HTML source code is virtually identical, except for a couple of things that RTD inserts, but they should not affect the search function.

**Comment by cguardia** [comment]
Something is not being triggered, but the search tools are initializing correctly. If you do "Search.performSearch('pyramid')" on the JS console, it works.

**Comment by cguardia** [comment]
Added simple workaround. Calling that "fixed".
