### ISSUE TITLE
Quick Find Feature

### ISSUE THREAD

**Issue by chrisrossi** [Pylons/substanced#290]
I am attaching a commit from my personal website where I implemented a Quick Find feature in case you guys would like to include something like this in Substance D proper.  You're welcome to use or not.  It's a little rough and would need more work to be a full fledged framework component.

The catalog piece is realized by hacking up the FieldIndex a little bit.  UI is Twitter typeahead, bugs and all.

[dusky_quickfind.txt](https://github.com/Pylons/substanced/files/417065/dusky_quickfind.txt)

**Comment by jogilder** [comment]
I would be interested in a quick find feature in our implemetation of substanced- @chrisrossi , can you provide an example of this working?
