### ISSUE TITLE
after installing substanced, scaffold is missing

### ISSUE THREAD

**Issue by waderock** [Pylons/substanced#301]
Setting up fresh python3.5 enviroment and installing substanced using PIP results in the following error.

Warning: could not load entry point substanced (ImportError: No module named 'pyramid.config.util')
Available scaffolds:
  alchemy:  Pyramid project using SQLAlchemy, SQLite, URL dispatch, and Jinja2
  starter:  Pyramid starter project using URL dispatch and Jinja2
  zodb:     Pyramid project using ZODB, traversal, and Chameleon

**Comment by stevepiercy** [comment]
What was you pip command? Please provide the complete output of that command.

**Comment by waderock** [comment]
bnns@ailinux:~/workspace/NSC$ virtualenv -p/usr/bin/python3 .
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/bnns/workspace/NSC/bin/python3
Also creating executable in /home/bnns/workspace/NSC/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
bnns@ailinux:~/workspace/NSC$ source bin/activate
(NSC) bnns@ailinux:~/workspace/NSC$ pip install --no-cache-dir substanced
Collecting substanced
  Downloading https://files.pythonhosted.org/packages/88/da/aa9292827794b9afcf2fcc75c4af1319483adc8d20edec80037511f25e4a/substanced-1.0a1.tar.gz (3.4MB)
    100% |████████████████████████████████| 3.4MB 1.7MB/s 
Collecting pyramid>=1.5dev (from substanced)
  Downloading https://files.pythonhosted.org/packages/d1/b7/fb7177c13d85f8713e782090cd0f3b34eb7f305f6b7212d154ca4cec8ba4/pyramid-1.10-py2.py3-none-any.whl (325kB)
    100% |████████████████████████████████| 327kB 1.6MB/s 
Collecting ZODB (from substanced)
  Downloading https://files.pythonhosted.org/packages/78/27/346776a8c1d9bcdfa1559688ae8461ccb2e5e876f275732d71aaf8529c9b/ZODB-5.5.1-py2.py3-none-any.whl (412kB)
    100% |████████████████████████████████| 419kB 2.1MB/s 
Collecting hypatia>=0.2 (from substanced)
  Downloading https://files.pythonhosted.org/packages/19/bc/4a0cccb3f35f5585f64257c0f07a378dc09150d94aa4e2d26536ef128e16/hypatia-0.3.tar.gz (139kB)
    100% |████████████████████████████████| 143kB 1.2MB/s 
Collecting venusian>=1.0a3 (from substanced)
  Downloading https://files.pythonhosted.org/packages/2f/c2/3d122e19287ed7d73f03821cef87e53673f27d41cae54ee3a46e92b147e2/venusian-1.1.0-py2.py3-none-any.whl
Collecting deform>=2.0a2 (from substanced)
  Downloading https://files.pythonhosted.org/packages/9d/a8/0e60d1ba7d55f9633136db2d415ffbcd0be2a91a6c645bb402fc0acd2534/deform-2.0.6-py3-none-any.whl (818kB)
    100% |████████████████████████████████| 819kB 1.9MB/s 
Collecting colander>=1.0a1 (from substanced)
  Downloading https://files.pythonhosted.org/packages/d2/6f/ea58d3e5a1f7c4d5ff3360d151d5dcedb0d927bb23b823d5a8b3cd951f49/colander-1.5.1-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 112kB 2.2MB/s 
Collecting pyramid_zodbconn>=0.6 (from substanced)
  Downloading https://files.pythonhosted.org/packages/3a/4f/7469f4ffedbcd2d3ff06a5d048b14f699c43e00a752ea9388e80c1074305/pyramid_zodbconn-0.8.1-py2.py3-none-any.whl
Collecting pyramid_chameleon (from substanced)
  Downloading https://files.pythonhosted.org/packages/8a/cd/ae2f1f2c547884bc6fa16aa607d21f8e85a0b7997b0ba6426e35212b1e2d/pyramid_chameleon-0.3.tar.gz
Collecting pyramid_mailer (from substanced)
  Downloading https://files.pythonhosted.org/packages/ea/c3/0ce593179a8da8e1ab7fe178b0ae096a046246bd44a5787f72940d6dd5b2/pyramid_mailer-0.15.1-py2.py3-none-any.whl
Collecting cryptacular (from substanced)
  Downloading https://files.pythonhosted.org/packages/73/bd/714b3fbfb3392d6b4e658638d9b74f77ce1072725209c08a6becd90836a7/cryptacular-1.4.1.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 19.4MB/s 
Collecting python-magic (from substanced)
  Downloading https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting PyYAML (from substanced)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 4.1MB/s 
Collecting zope.copy (from substanced)
  Downloading https://files.pythonhosted.org/packages/d3/11/740e1ea6dba4ce353855768826c9a4487edfb91d102e540a612dcf3481f2/zope.copy-4.2-py2.py3-none-any.whl
Collecting zope.component (from substanced)
  Downloading https://files.pythonhosted.org/packages/97/e2/c785df1171f277ea93cc16bdcc112cb3ddfde1aeefbc401d46c49727f472/zope.component-4.5-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 71kB 1.9MB/s 
Collecting zope.deprecation (from substanced)
  Downloading https://files.pythonhosted.org/packages/ee/33/625098914ec59b3006adf2cdf44a721e9671f4836af9eeb8cbe14e485954/zope.deprecation-4.3.0-py2.py3-none-any.whl
Collecting statsd (from substanced)
  Downloading https://files.pythonhosted.org/packages/47/33/c824f799128dfcfce2142f18d9bc6c55c46a939f6e4250639134222d99eb/statsd-3.3.0-py2.py3-none-any.whl
Collecting walkabout (from substanced)
  Downloading https://files.pythonhosted.org/packages/75/2a/1784ca619581a64d533c04eae56cd92492afc461a3eaa0e8b4b073dcb199/walkabout-0.10.tar.gz
Collecting pytz (from substanced)
  Downloading https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.9MB/s 
Collecting unidecode (from substanced)
  Downloading https://files.pythonhosted.org/packages/59/ef/67085e30e8bbcdd76e2f0a4ad8151c13a2c5bce77c85f8cad6e1f16fb141/Unidecode-1.0.22-py2.py3-none-any.whl (235kB)
    100% |████████████████████████████████| 235kB 3.8MB/s 
Collecting plaster (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/61/29/3ac8a5d03b2d9e6b876385066676472ba4acf93677acfc7360b035503d49/plaster-1.0-py2.py3-none-any.whl
Collecting translationstring>=0.4 (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/26/e7/9dcf5bcd32b3ad16db542845ad129c06927821ded434ae88f458e6190626/translationstring-1.3-py2.py3-none-any.whl
Collecting plaster-pastedeploy (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/d9/e2/de7cd499923dbf6aacc9b243f262817bfea3ffbbd4dcc5847e1aaec817a7/plaster_pastedeploy-0.6-py2.py3-none-any.whl
Collecting zope.interface>=3.8.0 (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/0c/dc/d715a3f2f9df4e0440e67b1dc654bcfb6dc11aac8296353eaf56164b8f01/zope.interface-4.6.0-cp35-cp35m-manylinux1_x86_64.whl (167kB)
    100% |████████████████████████████████| 174kB 1.7MB/s 
Requirement already satisfied: setuptools in ./lib/python3.5/site-packages (from pyramid>=1.5dev->substanced) (40.5.0)
Collecting hupper (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/29/04/9be87e39d7346daff2117af7505c2f5aa900965f29ce88f5a1f9ff670cf4/hupper-1.4-py2.py3-none-any.whl
Collecting webob>=1.8.3 (from pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/b5/74/a9aaec7ca6c94a58e379a9c95255a2b2017514948054c72c0d1a25953348/WebOb-1.8.3-py2.py3-none-any.whl (113kB)
    100% |████████████████████████████████| 122kB 2.6MB/s 
Collecting zc.lockfile (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/f5/fe/efb94907d8b2b81c3beab1bd628ff67e310d82816b94aa00b52062727ea9/zc.lockfile-1.3.0.tar.gz
Collecting six (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting zodbpickle>=1.0.1 (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/d5/cf/8eb48c65e58760acc42c86fa6246b746e9789e715155c7ed7999845b0b36/zodbpickle-1.0.2-cp35-cp35m-manylinux1_x86_64.whl (327kB)
    100% |████████████████████████████████| 327kB 1.5MB/s 
Collecting persistent>=4.4.0 (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/56/a3/b63bc36720b07c7f9c7f448d8fa338dc59633f606c6d4230a4a70f8c8d16/persistent-4.4.3.tar.gz (105kB)
    100% |████████████████████████████████| 112kB 1.2MB/s 
Collecting ZConfig (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/eb/b1/3ba00a8f9168414a07547162e588e6a5a5ecf6c28240cbcaac9a76dc7a1a/ZConfig-3.3.0-py2.py3-none-any.whl (119kB)
    100% |████████████████████████████████| 122kB 2.0MB/s 
Collecting BTrees>=4.2.0 (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/08/3c/9a7063b150f16d78e8895d7526404c5ba4a910b58a765a254576efe88279/BTrees-4.5.1-cp35-cp35m-manylinux1_x86_64.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.7MB/s 
Collecting transaction>=2.4 (from ZODB->substanced)
  Downloading https://files.pythonhosted.org/packages/21/38/499bcc737411b00ea969fdc82e1ff56925a0ea634fe03173e18fbdd59015/transaction-2.4.0-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 1.4MB/s 
Collecting peppercorn>=0.3 (from deform>=2.0a2->substanced)
  Downloading https://files.pythonhosted.org/packages/14/84/d8d9c3f17bda2b6f49406982546d6f6bc0fa188a43d4e3ba9169a457ee04/peppercorn-0.6-py3-none-any.whl
Collecting iso8601 (from deform>=2.0a2->substanced)
  Downloading https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Collecting Chameleon>=2.5.1 (from deform>=2.0a2->substanced)
  Downloading https://files.pythonhosted.org/packages/d0/59/ad925b5d098117fd6f339e6f7f29f98400ea11c5377f531ac55625909a5e/Chameleon-3.5.tar.gz (117kB)
    100% |████████████████████████████████| 122kB 2.3MB/s 
Collecting zodburi (from pyramid_zodbconn>=0.6->substanced)
  Downloading https://files.pythonhosted.org/packages/cd/ec/27599bc7003aa350913d572d7ce648a03fcb02cad3aa9620a52bef7d4b0e/zodburi-2.3.0.tar.gz
Collecting repoze.sendmail>=4.1 (from pyramid_mailer->substanced)
  Downloading https://files.pythonhosted.org/packages/25/98/c5c64dc045b7c45858c391d04673a0f2748acef8e0eea4f2989b22220f97/repoze.sendmail-4.4.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
Collecting pbkdf2 (from cryptacular->substanced)
  Downloading https://files.pythonhosted.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz
Collecting zope.hookable>=4.2.0 (from zope.component->substanced)
  Downloading https://files.pythonhosted.org/packages/41/b5/378175b959565de41f45c775cdfbf8897aaeaf29a258b94e40bd2661ce46/zope.hookable-4.2.0.tar.gz
Collecting zope.event (from zope.component->substanced)
  Downloading https://files.pythonhosted.org/packages/c5/96/361edb421a077a4c208b4a5c212737d78ae03ce67fbbcd01621c49f332d1/zope.event-4.4-py2.py3-none-any.whl
Collecting zope.deferredimport>=4.2.1 (from zope.component->substanced)
  Downloading https://files.pythonhosted.org/packages/62/d2/e03e4b0c9103817e19d1ea577c1f7fb9b67e4c0397ca5127d377e1eafe0c/zope.deferredimport-4.3-py2.py3-none-any.whl
Collecting PasteDeploy>=1.5.0 (from plaster-pastedeploy->pyramid>=1.5dev->substanced)
  Downloading https://files.pythonhosted.org/packages/31/28/51201a54aeecbd02eff767d17050b302f6fd98fdfecb4e3f4c9301ba6ef8/PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting ZEO (from zodburi->pyramid_zodbconn>=0.6->substanced)
  Downloading https://files.pythonhosted.org/packages/c4/cf/5e10a975effe9eea47bc502d29ce0735d3e145b7cddea5ec1b4aca858fce/ZEO-5.2.0.tar.gz (276kB)
    100% |████████████████████████████████| 276kB 2.0MB/s 
Collecting zope.proxy (from zope.deferredimport>=4.2.1->zope.component->substanced)
  Downloading https://files.pythonhosted.org/packages/7c/f5/e9ed65cdf8c93d24d7512ef89e21b241bc9ae75d90bc8608cc142f4c26f9/zope.proxy-4.3.1.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 2.9MB/s 
Collecting zdaemon (from ZEO->zodburi->pyramid_zodbconn>=0.6->substanced)
  Downloading https://files.pythonhosted.org/packages/cc/ee/da4e7cd4bc5127775de03c41e02b7a95ae3cafea352b28e0701c9a3369ab/zdaemon-4.3.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Installing collected packages: plaster, translationstring, PasteDeploy, plaster-pastedeploy, zope.interface, hupper, webob, venusian, zope.deprecation, pyramid, zc.lockfile, six, zodbpickle, persistent, ZConfig, BTrees, transaction, ZODB, hypatia, peppercorn, iso8601, colander, Chameleon, deform, zdaemon, ZEO, zodburi, pyramid-zodbconn, pyramid-chameleon, repoze.sendmail, pyramid-mailer, pbkdf2, cryptacular, python-magic, PyYAML, zope.copy, zope.hookable, zope.event, zope.proxy, zope.deferredimport, zope.component, statsd, walkabout, pytz, unidecode, substanced
  Running setup.py install for zc.lockfile ... done
  Running setup.py install for persistent ... done
  Running setup.py install for hypatia ... done
  Running setup.py install for Chameleon ... done
  Running setup.py install for zdaemon ... done
  Running setup.py install for ZEO ... done
  Running setup.py install for zodburi ... done
  Running setup.py install for pyramid-chameleon ... done
  Running setup.py install for pbkdf2 ... done
  Running setup.py install for cryptacular ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for zope.hookable ... done
  Running setup.py install for zope.proxy ... done
  Running setup.py install for walkabout ... done
  Running setup.py install for substanced ... done
Successfully installed BTrees-4.5.1 Chameleon-3.5 PasteDeploy-1.5.2 PyYAML-3.13 ZConfig-3.3.0 ZEO-5.2.0 ZODB-5.5.1 colander-1.5.1 cryptacular-1.4.1 deform-2.0.6 hupper-1.4 hypatia-0.3 iso8601-0.1.12 pbkdf2-1.3 peppercorn-0.6 persistent-4.4.3 plaster-1.0 plaster-pastedeploy-0.6 pyramid-1.10 pyramid-chameleon-0.3 pyramid-mailer-0.15.1 pyramid-zodbconn-0.8.1 python-magic-0.4.15 pytz-2018.7 repoze.sendmail-4.4.1 six-1.11.0 statsd-3.3.0 substanced-1.0a1 transaction-2.4.0 translationstring-1.3 unidecode-1.0.22 venusian-1.1.0 walkabout-0.10 webob-1.8.3 zc.lockfile-1.3.0 zdaemon-4.3 zodbpickle-1.0.2 zodburi-2.3.0 zope.component-4.5 zope.copy-4.2 zope.deferredimport-4.3 zope.deprecation-4.3.0 zope.event-4.4 zope.hookable-4.2.0 zope.interface-4.6.0 zope.proxy-4.3.1
(NSC) bnns@ailinux:~/workspace/NSC$ pcreate -l
Warning: could not load entry point substanced (ImportError: No module named 'pyramid.config.util')
Available scaffolds:
  alchemy:  Pyramid project using SQLAlchemy, SQLite, URL dispatch, and Jinja2
  starter:  Pyramid starter project using URL dispatch and Jinja2
  zodb:     Pyramid project using ZODB, traversal, and Chameleon

**Comment by stevepiercy** [comment]
We don't support installation that differs from https://docs.pylonsproject.org/projects/substanced/en/latest/install.html

**Comment by waderock** [comment]
bnns@ailinux:~/workspace/NSC$ virtualenv -p python2.7 hack-on-substanced
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/bnns/workspace/NSC/hack-on-substanced/bin/python2.7
Also creating executable in /home/bnns/workspace/NSC/hack-on-substanced/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
bnns@ailinux:~/workspace/NSC$ cd hack-on-substanced/
bnns@ailinux:~/workspace/NSC/hack-on-substanced$ bin/pip install -e git+https://github.com/Pylons/substanced#egg=substanced
Obtaining substanced from git+https://github.com/Pylons/substanced#egg=substanced
  Cloning https://github.com/Pylons/substanced to ./src/substanced
Collecting pyramid>=1.5dev (from substanced)
  Using cached https://files.pythonhosted.org/packages/d1/b7/fb7177c13d85f8713e782090cd0f3b34eb7f305f6b7212d154ca4cec8ba4/pyramid-1.10-py2.py3-none-any.whl
Collecting ZODB (from substanced)
  Using cached https://files.pythonhosted.org/packages/78/27/346776a8c1d9bcdfa1559688ae8461ccb2e5e876f275732d71aaf8529c9b/ZODB-5.5.1-py2.py3-none-any.whl
Collecting hypatia>=0.2 (from substanced)
Collecting venusian>=1.0a3 (from substanced)
  Using cached https://files.pythonhosted.org/packages/2f/c2/3d122e19287ed7d73f03821cef87e53673f27d41cae54ee3a46e92b147e2/venusian-1.1.0-py2.py3-none-any.whl
Collecting deform>=2.0a2 (from substanced)
Collecting colander>=1.0a1 (from substanced)
  Using cached https://files.pythonhosted.org/packages/d2/6f/ea58d3e5a1f7c4d5ff3360d151d5dcedb0d927bb23b823d5a8b3cd951f49/colander-1.5.1-py2.py3-none-any.whl
Collecting pyramid_zodbconn>=0.6 (from substanced)
  Using cached https://files.pythonhosted.org/packages/3a/4f/7469f4ffedbcd2d3ff06a5d048b14f699c43e00a752ea9388e80c1074305/pyramid_zodbconn-0.8.1-py2.py3-none-any.whl
Collecting pyramid_chameleon (from substanced)
Collecting pyramid_mailer (from substanced)
  Using cached https://files.pythonhosted.org/packages/ea/c3/0ce593179a8da8e1ab7fe178b0ae096a046246bd44a5787f72940d6dd5b2/pyramid_mailer-0.15.1-py2.py3-none-any.whl
Collecting cryptacular (from substanced)
  Using cached https://files.pythonhosted.org/packages/73/bd/714b3fbfb3392d6b4e658638d9b74f77ce1072725209c08a6becd90836a7/cryptacular-1.4.1.tar.gz
Collecting python-magic (from substanced)
  Using cached https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting PyYAML (from substanced)
Collecting zope.copy (from substanced)
  Using cached https://files.pythonhosted.org/packages/d3/11/740e1ea6dba4ce353855768826c9a4487edfb91d102e540a612dcf3481f2/zope.copy-4.2-py2.py3-none-any.whl
Collecting zope.component (from substanced)
  Using cached https://files.pythonhosted.org/packages/97/e2/c785df1171f277ea93cc16bdcc112cb3ddfde1aeefbc401d46c49727f472/zope.component-4.5-py2.py3-none-any.whl
Collecting zope.deprecation (from substanced)
  Using cached https://files.pythonhosted.org/packages/ee/33/625098914ec59b3006adf2cdf44a721e9671f4836af9eeb8cbe14e485954/zope.deprecation-4.3.0-py2.py3-none-any.whl
Collecting statsd (from substanced)
  Using cached https://files.pythonhosted.org/packages/47/33/c824f799128dfcfce2142f18d9bc6c55c46a939f6e4250639134222d99eb/statsd-3.3.0-py2.py3-none-any.whl
Collecting walkabout (from substanced)
Collecting pytz (from substanced)
  Using cached https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
Collecting unidecode (from substanced)
  Using cached https://files.pythonhosted.org/packages/59/ef/67085e30e8bbcdd76e2f0a4ad8151c13a2c5bce77c85f8cad6e1f16fb141/Unidecode-1.0.22-py2.py3-none-any.whl
Collecting hupper (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/29/04/9be87e39d7346daff2117af7505c2f5aa900965f29ce88f5a1f9ff670cf4/hupper-1.4-py2.py3-none-any.whl
Collecting translationstring>=0.4 (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/26/e7/9dcf5bcd32b3ad16db542845ad129c06927821ded434ae88f458e6190626/translationstring-1.3-py2.py3-none-any.whl
Collecting zope.interface>=3.8.0 (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/a2/a2/e68c37eb2ef9bf942e0ace19f4cf6fe3e7c650932fb587bfde3c608f7d77/zope.interface-4.6.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting plaster (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/61/29/3ac8a5d03b2d9e6b876385066676472ba4acf93677acfc7360b035503d49/plaster-1.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages (from pyramid>=1.5dev->substanced) (40.5.0)
Collecting plaster-pastedeploy (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/d9/e2/de7cd499923dbf6aacc9b243f262817bfea3ffbbd4dcc5847e1aaec817a7/plaster_pastedeploy-0.6-py2.py3-none-any.whl
Collecting repoze.lru>=0.4; python_version < "3.2" (from pyramid>=1.5dev->substanced)
Collecting webob>=1.8.3 (from pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/b5/74/a9aaec7ca6c94a58e379a9c95255a2b2017514948054c72c0d1a25953348/WebOb-1.8.3-py2.py3-none-any.whl
Collecting six (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting BTrees>=4.2.0 (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/25/48/1536c3b2d8e1322d25b598d019e4477145256947cd827807ea83e52cda3f/BTrees-4.5.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting zodbpickle>=1.0.1 (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/0f/16/d32a8f2e66a871a02d20adbc0e32a8d755a9541d8e6517bce15e1c2a84cc/zodbpickle-1.0.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting zc.lockfile (from ZODB->substanced)
Collecting persistent>=4.4.0 (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/56/a3/b63bc36720b07c7f9c7f448d8fa338dc59633f606c6d4230a4a70f8c8d16/persistent-4.4.3.tar.gz
Collecting transaction>=2.4 (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/21/38/499bcc737411b00ea969fdc82e1ff56925a0ea634fe03173e18fbdd59015/transaction-2.4.0-py2.py3-none-any.whl
Collecting ZConfig (from ZODB->substanced)
  Using cached https://files.pythonhosted.org/packages/eb/b1/3ba00a8f9168414a07547162e588e6a5a5ecf6c28240cbcaac9a76dc7a1a/ZConfig-3.3.0-py2.py3-none-any.whl
Collecting Chameleon>=2.5.1 (from deform>=2.0a2->substanced)
Collecting peppercorn>=0.3 (from deform>=2.0a2->substanced)
Collecting iso8601 (from deform>=2.0a2->substanced)
  Using cached https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Collecting enum34; python_version in "2.7,3.3" (from colander>=1.0a1->substanced)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting zodburi (from pyramid_zodbconn>=0.6->substanced)
  Using cached https://files.pythonhosted.org/packages/35/7f/9b8a01b17c5d1e7ed97751e9bf017052ef7019ca2f21b4c58bfe5a6f9b95/zodburi-2.3.0-py2-none-any.whl
Collecting repoze.sendmail>=4.1 (from pyramid_mailer->substanced)
  Using cached https://files.pythonhosted.org/packages/25/98/c5c64dc045b7c45858c391d04673a0f2748acef8e0eea4f2989b22220f97/repoze.sendmail-4.4.1-py2.py3-none-any.whl
Collecting pbkdf2 (from cryptacular->substanced)
Collecting zope.hookable>=4.2.0 (from zope.component->substanced)
Collecting zope.deferredimport>=4.2.1 (from zope.component->substanced)
  Using cached https://files.pythonhosted.org/packages/62/d2/e03e4b0c9103817e19d1ea577c1f7fb9b67e4c0397ca5127d377e1eafe0c/zope.deferredimport-4.3-py2.py3-none-any.whl
Collecting zope.event (from zope.component->substanced)
  Using cached https://files.pythonhosted.org/packages/c5/96/361edb421a077a4c208b4a5c212737d78ae03ce67fbbcd01621c49f332d1/zope.event-4.4-py2.py3-none-any.whl
Collecting PasteDeploy>=1.5.0 (from plaster-pastedeploy->pyramid>=1.5dev->substanced)
  Using cached https://files.pythonhosted.org/packages/31/28/51201a54aeecbd02eff767d17050b302f6fd98fdfecb4e3f4c9301ba6ef8/PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting ZEO (from zodburi->pyramid_zodbconn>=0.6->substanced)
Collecting zope.proxy (from zope.deferredimport>=4.2.1->zope.component->substanced)
Collecting zdaemon (from ZEO->zodburi->pyramid_zodbconn>=0.6->substanced)
Collecting trollius; python_version == "2.7" (from ZEO->zodburi->pyramid_zodbconn>=0.6->substanced)
Collecting futures; python_version == "2.7" (from ZEO->zodburi->pyramid_zodbconn>=0.6->substanced)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Building wheels for collected packages: cryptacular, persistent
  Running setup.py bdist_wheel for cryptacular ... done
  Stored in directory: /home/bnns/.cache/pip/wheels/05/cd/1f/64fb0fb06f2735e2ca898935061275465573db7f4f98fa1db4
  Running setup.py bdist_wheel for persistent ... done
  Stored in directory: /home/bnns/.cache/pip/wheels/2d/45/77/d75d81e64620b4753ff6b1d83ec8ab80dbd4eb260b94c9885f
Successfully built cryptacular persistent
Installing collected packages: hupper, translationstring, zope.interface, plaster, zope.deprecation, PasteDeploy, plaster-pastedeploy, venusian, repoze.lru, webob, pyramid, six, persistent, BTrees, zodbpickle, zc.lockfile, transaction, ZConfig, ZODB, hypatia, Chameleon, peppercorn, enum34, iso8601, colander, deform, zdaemon, futures, trollius, ZEO, zodburi, pyramid-zodbconn, pyramid-chameleon, repoze.sendmail, pyramid-mailer, pbkdf2, cryptacular, python-magic, PyYAML, zope.copy, zope.hookable, zope.proxy, zope.deferredimport, zope.event, zope.component, statsd, walkabout, pytz, unidecode, substanced
  Running setup.py develop for substanced
Successfully installed BTrees-4.5.1 Chameleon-3.5 PasteDeploy-1.5.2 PyYAML-3.13 ZConfig-3.3.0 ZEO-5.2.0 ZODB-5.5.1 colander-1.5.1 cryptacular-1.4.1 deform-2.0.6 enum34-1.1.6 futures-3.2.0 hupper-1.4 hypatia-0.3 iso8601-0.1.12 pbkdf2-1.3 peppercorn-0.6 persistent-4.4.3 plaster-1.0 plaster-pastedeploy-0.6 pyramid-1.10 pyramid-chameleon-0.3 pyramid-mailer-0.15.1 pyramid-zodbconn-0.8.1 python-magic-0.4.15 pytz-2018.7 repoze.lru-0.7 repoze.sendmail-4.4.1 six-1.11.0 statsd-3.3.0 substanced transaction-2.4.0 translationstring-1.3 trollius-2.2 unidecode-1.0.22 venusian-1.1.0 walkabout-0.10 webob-1.8.3 zc.lockfile-1.3.0 zdaemon-4.3 zodbpickle-1.0.2 zodburi-2.3.0 zope.component-4.5 zope.copy-4.2 zope.deferredimport-4.3 zope.deprecation-4.3.0 zope.event-4.4 zope.hookable-4.2.0 zope.interface-4.6.0 zope.proxy-4.3.1
bnns@ailinux:~/workspace/NSC/hack-on-substanced$ bin/pcreate -l
Warning: could not load entry point substanced (ImportError: No module named util)
Available scaffolds:
  alchemy:  Pyramid project using SQLAlchemy, SQLite, URL dispatch, and Jinja2
  starter:  Pyramid starter project using URL dispatch and Jinja2
  zodb:     Pyramid project using ZODB, traversal, and Chameleon
bnns@ailinux:~/workspace/NSC/hack-on-substanced$

**Comment by stevepiercy** [comment]
Why do you skip all the steps starting from Step 3 in the installation docs?

What do you expect `bin/pcreate -l` to do?

**Comment by waderock** [comment]
Sorry about that, here comes the next step 

bnns@ailinux:~/workspace/NSC/hack-on-substanced$ bin/python -c "from substanced.file import magic; assert magic is not None, 'python-magic not installed'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bnns/workspace/NSC/hack-on-substanced/src/substanced/substanced/__init__.py", line 1, in <module>
    from .db import root_factory # b/c
  File "/home/bnns/workspace/NSC/hack-on-substanced/src/substanced/substanced/db/__init__.py", line 7, in <module>
    from substanced.evolution import mark_unfinished_as_finished
  File "/home/bnns/workspace/NSC/hack-on-substanced/src/substanced/substanced/evolution/__init__.py", line 5, in <module>
    from pyramid.config.util import takes_one_arg
ImportError: No module named util

I expect pcreate -l to list substanced as a optional scaffold for the project, but due to import error related to pyramid.config.util, it looks like the behaviour is different than expected.

**Comment by stevepiercy** [comment]
OK. Thanks for the additional information. I'll defer to the maintainers at this point, as I don't have any clue as to what the issue might be.

Meanwhile you could try the [substanced cookiecutter](https://github.com/pylons/substanced-cookiecutter) as an alternate installation method.

**Comment by waderock** [comment]
I seem like changing 

from pyramid.config.util import takes_one_arg

to 

from pyramid.util import takes_one_arg

in /substanced/substanced/evolution/init.py"
resolves the issue

**Comment by waderock** [comment]
substanced/property/__init__.py", line 9, in <module>
from pyramid.config.util import action_method
ImportError: No module named 'pyramid.config.util'
Moved to
from pyramid.config.actions import action_method

**Comment by stevepiercy** [comment]
Would you please submit a PR with your suggested change so that the maintainers can review and merge your fix? Thank you!

**Comment by cguardia** [comment]
Pyramid 1.10 removed a few deprecated backwards compatibility shims. @waderock were the changes you mentioned here enough to get it working? Thanks a lot for reporting!

**Comment by cguardia** [comment]
@waderock never mind, fixed on master.

**Comment by cguardia** [comment]
Made a new release too: https://pypi.org/manage/project/substanced/release/1.0/

**Comment by stevepiercy** [comment]
Correct link, as the public are not managers:
https://pypi.org/project/substanced/1.0/

**Comment by cguardia** [comment]
Oops, sorry about that. Thanks a lot @stevepiercy!
