### ISSUE TITLE
Substanced doesn't work with Pyramid 1.10

### ISSUE THREAD

**Issue by digitalresistor** [Pylons/substanced#302]
Due to #301 I noticed that the current master of SubstanceD does not work with Pyramid 1.10.

**Comment by cguardia** [comment]
Right. Thanks a lot. Will take a look.

**Comment by bertjwregeer** [comment]
@cguardia No worries. Only added this ticket so that it can easily be tracked :-) Was going to take a look later tonight to see how difficult it would be to get tests to pass again.

**Comment by cguardia** [comment]
Thanks a lot @bertjwregeer, fixed the tests.

**Comment by cguardia** [comment]
https://pypi.org/manage/project/substanced/release/1.0/

**Comment by cguardia** [comment]
Not intentional. Just ran sdist and b_wheel and uploaded. Will review.

**Comment by bertjwregeer** [comment]
@cguardia there is no `MANIFEST.in` in this project, make sure you have `setuptools_git` installed when running `python setup.py sdist bdist_wheel`.

**Comment by jordic** [comment]
Hey, I'm just trying to install it without luck... seems like the issue from the locales...

**Comment by cguardia** [comment]
Sorry for my bad pypi skills. Should install now.

**Comment by waderock** [comment]
it seems that the updated sdi/__init__.py didn't make it to pypi.

**Comment by waderock** [comment]
any way that i can contribute to get the install from pypi working

**Comment by tseaver** [comment]
Apologies for the long delay.  I am able to install into a fresh virtualenv (note the need to pin `pyramid<2.0dev`):
```bash
$ python3.8 -m venv /tmp/sd-302
$ /tmp/sd-302/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-24.0 setuptools-69.5.1
$ /tmp/sd-302/bin/pip install "pyramid<2.0dev" substanced
...
Successfully installed BTrees-5.2 Chameleon-4.4.4 PasteDeploy-3.1.0 PyYAML-6.0.1 ZConfig-4.1 ZEO-6.0.0 ZODB-6.0 cffi-1.16.0 colander-2.0 cryptacular-1.6.2 deform-2.0.15 hupper-1.12.1 hypatia-0.4 importlib-metadata-7.1.0 importlib-resources-6.4.0 iso8601-2.1.0 pbkdf2-1.3 peppercorn-0.6 persistent-5.2 plaster-1.1.2 plaster-pastedeploy-1.0.1 pycparser-2.22 pyramid-1.10.8 pyramid-chameleon-0.3 pyramid-mailer-0.15.1 pyramid-zodbconn-0.8.1 python-magic-0.4.27 pytz-2024.1 repoze.sendmail-4.4.1 statsd-4.0.1 substanced-1.0.post1 transaction-4.0 translationstring-1.4 unidecode-1.3.8 venusian-3.1.0 walkabout-0.10 webob-1.8.7 zc.lockfile-3.0.post1 zdaemon-5.1 zipp-3.18.1 zodbpickle-3.3 zodburi-2.6.0 zope.component-6.0 zope.copy-4.3 zope.deprecation-5.0 zope.event-5.0 zope.hookable-6.0 zope.interface-6.3

```
